### ISSUE TITLE
Adding node to BST

### ISSUE THREAD

**Issue by jenyaftw** [gnomedb/GnomeDB#10]
Add method to BST class for adding a node to the tree.

**Comment by jenyaftw** [comment]
PR #14 solves this. But keeping it open for future improvements for indexing

**Comment by jenyaftw** [comment]
PR #16 adds storing data in Set instead

**Comment by artemkaxdxd** [comment]
I optimized some of your code in PR #26

**Comment by jenyaftw** [comment]
@artemkaxdxd Thanks, merged it
