### ISSUE TITLE
Finding data entries

### ISSUE THREAD

**Issue by jenyaftw** [gnomedb/GnomeDB#49]
A method for finding database entries needs to be written in data store class.
This needs to work efficiently with and without indexing.
Will be worked on after PR #46 is finished, as it is an essential part of this.

**Comment by dyachaliin** [comment]
Fixed Isssues with `getNodesLessThan()` and `getNodesGreaterThan()` methods in PR #56

**Comment by artemkaxdxd** [comment]
Fixed methods `filterGreaterThan()`/`filterLessThan()` in bst,js and optimised `find()` method in store.js in PR #57

**Comment by mykolachub** [comment]
`find()` method improved again.. in PR #59

**Comment by artemkaxdxd** [comment]
Solved issue in PR #55 - #59
